name: Roblib Geocode Lookup
type: module
description: Takes entity Address field and populates entity with geocode data from Google.
core: 8.x
package: Roblib
dependencies:
  - address
  - geolocation
